## Deployment playbook goes here.
---
#- name: "upgrade packages."
#  become: true
#  apt:
#    upgrade: "yes"
#
#- name: "install dependencies."
#  become: true
#  apt:
#    name: ["nodejs", "npm"]
#    state: latest
#    update_cache: yes
#
#- name: "install pm2"
#  become: true
#  npm:
#    name: pm2
#    global: yes
#    production: yes
#    state: present

#- name: "Make backend dir"
#  file:
#    path: /home/ubuntu/backend
#    state: directory
#- name: unpack backend files
#  become: yes
#  shell: |
#    pwd

###############
#- name: create backend directory
#  become: yes
#  file:
#    path: ~/home/ubuntu/backend
#    state: directory
#    mode: 0755
#
#- name: copy backend files
#  become: yes
#  copy:
#    src: ~/project/artifact.tar.gz
#    dest: ~/home/ubuntu/backend/artifact.tar.gz
#
#- name: unpack backend files
#  become: yes
#  shell: |
#    cd ~/home/ubuntu/backend
#    tar -vxf artifact.tar.gz
#    rm -f artifact.tar.gz
#
#- name: start app 
#  become: yes
#  shell: |
#    cd ~/home/ubuntu/backend
#    npm install
#    pm2 stop default
#    pm2 start npm -- start
#    cd dist
#    pm2 start main.js --update-env

- name: "Copy dist backend directory to EC2 server"
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
- name: "Install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "python3", "tar", "gzip", "git"]
    state: latest
    update_cache: yes
- name: "Create directory for backend"
  file:
    path: /home/ubuntu/backend/
    state: directory
- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .
- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm --name backend -- start
